use restaurant_db;

select * from customers;
select * from menu;
select * from sales;

select count(*) as total_customers
from customers;

select count(*) as total_menu_items
from menu;

select count(*) as total_orders
from sales;

-- total revenue
select
sum(total_bill) as total_revenue
from sales;

-- average bill amount
select
avg(total_bill) as average_bill
from sales;

-- highest bill
select
max(total_bill) as highest_bill
from sales;

-- lowest bill
select
min(total_bill) as lowest_bill
from sales;

-- total quantity sold
select
sum(quantity) as total_items_sold
from sales;

-- best selling dishes
select
    m.dish_name,
    sum(s.quantity) as total_quantity_sold
from sales s
join menu m
on s.dish_id = m.dish_id
group by m.dish_name
order by total_quantity_sold desc;

-- revenue generated by each dish
select
    m.dish_name,
    sum(s.total_bill) as total_revenue
from sales s
join menu m
on s.dish_id = m.dish_id
group by m.dish_name
order by total_revenue desc;

-- revenue by category
select
    m.category,
    sum(s.total_bill) as revenue
from sales s
join menu m
on s.dish_id = m.dish_id
group by m.category
order by revenue desc;

-- top spending customers
select
    c.customer_name,
    sum(s.total_bill) as total_spent
from sales s
join customers c
on s.customer_id = c.customer_id
group by c.customer_name
order by total_spent desc;

-- revenue by city
select
    c.city,
    sum(s.total_bill) as revenue
from sales s
join customers c
on s.customer_id = c.customer_id
group by c.city
order by revenue desc;

-- revenue by membership
select
    c.membership,
    sum(s.total_bill) as revenue
from sales s
join customers c
on s.customer_id = c.customer_id
group by c.membership
order by revenue desc;

-- most used payment method
select
    payment_method,
    count(*) as number_of_orders
from sales
group by payment_method
order by number_of_orders desc;

-- peak ordering hours
select
    hour(order_time) as hour_of_day,
    count(*) as total_orders
from sales
group by hour_of_day
order by total_orders desc;